# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89fb2ff4186093fbf9b00d2ff7114a4f5f72ced8416f3dc9b97dffc6cc501f8c961f899d65068365b8f7bc1e2b5866bb6ecf8ead4f1fdc8d101df45d7563530b

test:
  secret_key_base: 15d9cb876d7c379800f4a4f770002d115f5e324ee5d4dad8c70eafeb283440e61dd0ca65186310e9136cb9a3d36626c9a4bfe835d5aa4b2d3ed1b7ff5022527a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
